TECH-1140 Code review changes

diff --git a/.github/actions/deploy-staging/action.yml b/.github/actions/deploy-staging/action.yml
--- a/.github/actions/deploy-staging/action.yml
+++ b/.github/actions/deploy-staging/action.yml
@@ -8,20 +8,62 @@ inputs:
 runs:
   using: "composite"
   steps:
-    - name: Upload Pacts
+    - uses: tibdex/github-app-token@v2
+      id: generate-token
+      with:
+        app_id: ${{ fromJSON(inputs.secrets).AUTODEPLOYER_ID }}
+        private_key: ${{ fromJSON(inputs.secrets).AUTODEPLOYER_KEY }}
+
+    - name: Trigger deployments
       shell: bash
+      env:
+        DEPLOYER_TOKEN: ${{ steps.generate-token.outputs.token }}
       run: |
-        set -ue ;
-        for PACT_DIR in $( find . | grep build/pacts$ | sed 's/^.\///' ) ; do
-          echo "Uploading pacts in: ${PACT_DIR}"
-          docker run --rm \
-           -w ${PWD} \
-           -v ${PWD}:${PWD} \
-           -e PACT_BROKER_BASE_URL=${{ fromJSON(inputs.secrets).PACT_BROKER_BASE_URL }} \
-           -e PACT_BROKER_USERNAME=${{ fromJSON(inputs.secrets).PACT_BROKER_USERNAME }} \
-           -e PACT_BROKER_PASSWORD=${{ fromJSON(inputs.secrets).PACT_BROKER_PASSWORD }} \
-            pactfoundation/pact-cli:0.50.0.27 \
-            publish \
-            ${PWD}/${PACT_DIR} \
-            --consumer-app-version "${{ env.VERSION }}"
+        set -ue
+        
+        REPOSITORY_NAME='${{ env.REPOSITORY_NAME }}'
+        VERSION='${{ env.VERSION }}'
+        
+        for env in $( ls auto-deploy/*.env.json ) ; do
+        
+          ENVIRONMENT=$( jq -r '.environment' "$env" )
+          COMPONENT=$( jq -r '.component' "$env" )
+          SERVICE=$( jq -r '.service' "$env" )
+        
+          if [ -z "$ENVIRONMENT" ] || [ "$ENVIRONMENT" = "null" ] ; then
+            echo "ERROR: Missing environment in $env"
+            exit 1
+          fi
+        
+          if [ -z "$COMPONENT" ] || [ "$COMPONENT" = "null" ] ; then
+            COMPONENT="$REPOSITORY_NAME"
+          fi
+        
+          if [ -z "$SERVICE" ]|| [ "$SERVICE" = "null" ] ; then
+            SERVICE="$REPOSITORY_NAME"
+          fi
+        
+          DISPATCH_EVENT="$REPOSITORY_NAME calls update version to $VERSION for $COMPONENT/$SERVICE in $ENVIRONMENT"
+        
+          BODY='{
+            "event_type": "update_version_event",
+            "client_payload": {
+              "dispatch_event": "'"$DISPATCH_EVENT"'",
+              "environment": "'"$ENVIRONMENT"'",
+              "component": "'"$COMPONENT"'",
+              "service": "'"$SERVICE"'",
+              "version": "'"$VERSION"'"
+            }
+          }'
+        
+          echo "$DISPATCH_EVENT"
+        
+          curl -H "Accept: application/vnd.github.everest-preview+json" \
+            -H "Authorization: token ${DEPLOYER_TOKEN}" \
+            --request POST \
+            --data "${BODY}" \
+            https://api.github.com/repos/sympower/environments/dispatches
+        
+          echo "Done: $DISPATCH_EVENT"
+        
         done
