TECH-886 Auto deployment script

diff --git a/.github/workflows/release-new-version.yml b/.github/workflows/release-new-version.yml
--- a/.github/workflows/release-new-version.yml
+++ b/.github/workflows/release-new-version.yml
@@ -227,6 +227,69 @@ jobs:
               --consumer-app-version "${{ env.VERSION }}"
           done
 
+      - uses: tibdex/github-app-token@v1
+        id: generate-token
+        with:
+          app_id: ${{ secrets.AUTODEPLOYER_ID }}
+          private_key: ${{ secrets.AUTODEPLOYER_KEY }}
+
+      - name: Trigger deployments
+        env:
+          DEPLOYER_TOKEN: ${{ steps.generate-token.outputs.token }}
+        if :
+          contains('
+          refs/heads/main
+          refs/heads/master
+          ', github.ref)
+        run: |
+          set -ue
+  
+          REPOSITORY_NAME='${{ env.REPOSITORY_NAME }}'
+          VERSION='${{ env.VERSION }}'
+          
+          for env in $( ls auto-deploy/*.env.json ) ; do
+        
+            ENVIRONMENT=$( jq -r '.environment' "$env" )
+            COMPONENT=$( jq -r '.component' "$env" )
+            SERVICE=$( jq -r '.service' "$env" )
+          
+            if [ -z "$ENVIRONMENT" ] || [ "$ENVIRONMENT" = "null" ] ; then
+              echo "ERROR: Missing environment in $env"
+              exit 1
+            fi
+            
+            if [ -z "$COMPONENT" ] || [ "$COMPONENT" = "null" ] ; then
+            COMPONENT="$REPOSITORY_NAME"
+            fi
+            
+            if [ -z "$SERVICE" ]|| [ "$SERVICE" = "null" ] ; then
+            SERVICE="$REPOSITORY_NAME"
+            fi
+          
+            DISPATCH_EVENT="$REPOSITORY_NAME calls update version to $VERSION for $COMPONENT/$SERVICE in $ENVIRONMENT"
+          
+            BODY='{
+              "event_type": "update_version_event",
+              "client_payload": {
+                "dispatch_event": "'"$DISPATCH_EVENT"'",
+                "environment": "'"$ENVIRONMENT"'",
+                "component": "'"$COMPONENT"'",
+                "service": "'"$SERVICE"'",
+                "version": "'"$VERSION"'"
+              }
+            }'
+        
+            echo "$DISPATCH_EVENT"
+          
+            echo curl -H "Accept: application/vnd.github.everest-preview+json" \
+              -H "Authorization: token ${DEPLOYER_TOKEN}" \
+              --request POST \
+              --data "${BODY}" \
+              https://api.github.com/repos/sympower/environments/dispatches
+          
+          done    
+
+
 #      - name: Upload build results
 #        uses: actions/upload-artifact@v3
 #        if: always()
